<?php
$this->pageTitle=Yii::app()->name . ' - 商品列表';
Yii::app()->clientScript->registerLinkTag('stylesheet/less', 'text/css', Yii::app()->baseUrl.'/css/admin/product.less');
?>
<article>
<?php $this->widget('zii.widgets.grid.CGridView', array(
		'id'=>'product_grid_view',
		'dataProvider'=>$product->search(),
		'filter'=>$product,
		'columns'=>array(
			array(
				'name'=>'id',
				'sortable'=>false,
			),
			array(
				'name'=>'name',
				'sortable'=>false,
			),
			array(
				'name'=>'price',
				'sortable'=>false,
			),
			array(
				'name'=>'publishTime',
				'sortable'=>true,
			),
			array(
				'name'=>'categoryId',
				'header'=>'分类',
				'filter'=>CHtml::listData(Category::model()->findAll(array('order'=>'name')), 'id', 'name'),
				'value'=>'$data->category->name',
			),
			array(
				'name'=>'isOnSale',
				'filter'=>$product->statusLabels(),
				'value'=>'$data->getStatusLabel($data->isOnSale)',
			),
			array(
				'class'=>'CButtonColumn',
				'buttons'=>array(
					'view'=>array(
						'url'=>'Yii::app()->createUrl("product/view", array("id"=>$data->id))',
						'options'=>array(
							'target'=>'_blank',
						),
					),
					'update'=>array(
						'options'=>array(
							'target'=>'_blank',
						),
					),
					'delete'=>array(
						'label'=>'下架',
					),
				),
				'deleteConfirmation'=>'确定要将该商品下架吗',
				'header'=>'可选操作',
			),
		),
		'pager'=>array(
			'header'=>'',
		),
	));
?>
<article>